#!/bin/bash


CACHEDIR=~/.wall-of-day
LINK=http://photography.nationalgeographic.com/photography/photo-of-the-day/

# Get the link.
# From Jaseem

IMAGE=$(curl -s ${LINK} | grep 'Download Wallpaper' | grep -Po 'http.*.jpg')
IMAGENAME=$(echo $IMAGE| awk -F "/" '{print $NF}')

if [ -z "${IMAGENAME}" ]
then
	echo "Non sharable image. :-("
	exit
fi


# Set up directories
if [ -d ${CACHEDIR} ]
then
    rm -rf ${CACHEDIR}
    mkdir ${CACHEDIR}
else
    mkdir $CACHEDIR
fi


IMAGENAME=${CACHEDIR}/$IMAGENAME}

curl -S $IMAGE > ${IMAGENAME}

gsettings set org.gnome.desktop.background picture-uri file://${IMAGENAME}

#gsettings set org.gnome.desktop.background picture-options centered
## Possible values: centered, none, scaled, spanned, stretched, wallpaper, zoom
